name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        xcodebuild test "-workspace" "LondonBusTimes.xcworkspace" -scheme 'LondonBusTimes' -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 8 Plus' | xcpretty "--color"
